const songsData = [
    {
        "songName": "通天大道宽又阔",
        "workName": "西游记",
        "impression": "印象深刻",
        "releaseYear": "1988",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1VZ421U7NP/",
        "cover": "images/西游记.webp",
        "description": "经典电视剧《西游记》的主题曲，由许镜清作曲，蒋大为演唱。这首歌气势磅礴，充满豪情壮志，完美展现了取经路上的艰辛与决心。'通天大道宽又阔'的歌词激励着一代又一代人勇往直前，成为了中国影视音乐的经典之作。每当熟悉的旋律响起，就能想起师徒四人历经九九八十一难的取经之路。"
    },
    {
        "songName": "目标是神奇宝贝大师",
        "workName": "神奇宝贝（口袋妖怪/宝可梦）",
        "impression": "印象深刻",
        "releaseYear": "1997",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV14A411u7Tg/",
        "cover": "images/神奇宝贝.webp",
        "description": "日本经典动画《神奇宝贝》的主题曲，讲述了少年小智立志成为神奇宝贝大师的梦想。歌曲充满了热血与激情，'要成为最伟大的神奇宝贝训练师'的歌词激励了无数孩子追逐自己的梦想。这首歌陪伴着小智和皮卡丘的冒险旅程，也陪伴着一代人的童年。"
    },
    {
        "songName": "猴哥",
        "workName": "西游记（动漫）",
        "impression": "印象深刻",
        "releaseYear": "1999",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1kT4y1D7B3/",
        "cover": "images/西游记动漫.webp",
        "description": "动画版《西游记》的主题曲，由张伟进作词作曲。轻快活泼的旋律完美诠释了孙悟空机智勇敢的形象，'猴哥猴哥你真了不得，五行大山压不住你'成为了经典歌词。这首歌朗朗上口，深受小朋友喜爱，成为了90年代末中国动画的代表作之一。"
    },
    {
        "songName": "小哪吒",
        "workName": "哪吒传奇",
        "impression": "印象深刻",
        "releaseYear": "2003",
        "singer": "孙楠",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1g4411u74A/",
        "cover": "images/哪吒传奇.webp",
        "description": "由孙楠演唱的动画《哪吒传奇》主题曲，讲述了少年英雄哪吒的成长故事。歌曲旋律激昂，充满了正义感和英雄气概。'是他，是他，就是他，我们的朋友小哪吒'的歌词深入人心，展现了哪吒不畏强权、勇敢正义的形象。这首歌激励着孩子们学习哪吒的勇气和善良。"
    },
    {
        "songName": "月亮船",
        "workName": "快乐星球",
        "impression": "有一些印象",
        "releaseYear": "2003",
        "singer": "",
        "type": "片尾曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1oM4y1e7Kx/",
        "cover": "images/快乐星球.webp",
        "description": "科幻儿童剧《快乐星球》的片尾曲，温馨动听的旋律伴随着每一集的结束。歌曲描绘了一个充满幻想的世界，月亮船载着孩子们的梦想驶向远方。这首歌让人感到温暖和治愈，成为了许多人童年回忆中温柔的一部分。"
    },
    {
        "songName": "快乐小神仙",
        "workName": "快乐星球",
        "impression": "有一些印象",
        "releaseYear": "2003",
        "singer": "",
        "type": "片头曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1r4411K7Gh/",
        "cover": "images/快乐星球.webp",
        "description": "《快乐星球》的片头曲，欢快的节奏开启每一集的冒险之旅。歌曲充满了童真和活力，描绘了乐乐和快乐星球小伙伴们的奇妙故事。这首歌让孩子们相信，只要保持快乐的心态，每个人都可以成为小神仙。"
    },
    {
        "songName": "Jackie Chan Adventures",
        "workName": "成龙历险记",
        "impression": "印象深刻",
        "releaseYear": "2004",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/bangumi/play/ep750897",
        "cover": "images/成龙历险记.webp",
        "description": "美国动画《成龙历险记》的主题曲，充满了冒险和动作元素。歌曲节奏明快，展现了成龙大叔和侄女小玉寻找十二生肖符咒的冒险故事。动画将成龙的功夫电影风格与魔法冒险完美结合，主题曲也充满了东西方文化融合的特色。"
    },
    {
        "songName": "奇迹再现",
        "workName": "迪迦奥特曼",
        "impression": "印象深刻",
        "releaseYear": "2004",
        "singer": "毛华锋",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1VB4y1X7UC/",
        "cover": "images/迪迦奥特曼.webp",
        "description": "由毛华锋演唱的《迪迦奥特曼》中文主题曲，充满了正能量和希望。'就像阳光穿过黑夜，黎明悄悄划过天边'的歌词深入人心，传递着光明必将战胜黑暗的信念。这首歌激励着无数孩子相信光的力量，成为奥特曼系列在中国最经典的主题曲之一。"
    },
    {
        "songName": "围棋少年",
        "workName": "围棋少年",
        "impression": "基本无印象",
        "releaseYear": "2005",
        "singer": "",
        "type": "片头曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1gx411v7jS/",
        "cover": "images/围棋少年.webp",
        "description": "动画《围棋少年》的片头曲，讲述了明朝少年江流儿学习围棋、追求棋道的故事。歌曲将中国传统文化与少年成长完美结合，展现了围棋的深奥与魅力。这部动画通过围棋文化传递着智慧、坚持和成长的主题。"
    },
    {
        "songName": "别看我只是一只羊",
        "workName": "喜羊羊与灰太狼",
        "impression": "印象深刻",
        "releaseYear": "2005",
        "singer": "",
        "type": "",
        "bilibiliLink": "https://www.bilibili.com/video/BV1X64y1d77T/",
        "cover": "images/喜羊羊与灰太狼.webp",
        "description": "国民动画《喜羊羊与灰太狼》的主题曲，轻快活泼的旋律让人过耳不忘。'别看我只是一只羊，绿草因为我变得更香'的歌词充满了自信和乐观。这首歌陪伴了整整一代人的童年，喜羊羊和灰太狼的故事也成为了中国动画的经典IP。"
    },
    {
        "songName": "人生如棋",
        "workName": "围棋少年",
        "impression": "基本无印象",
        "releaseYear": "2005",
        "singer": "",
        "type": "片尾曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV16P4y1w72u/",
        "cover": "images/围棋少年.webp",
        "description": "《围棋少年》的片尾曲，歌曲意境深远，通过围棋隐喻人生。'人生如棋，落子无悔'的主题贯穿其中，传递着中国传统哲学智慧。这首歌让孩子们在欣赏动画的同时，也能感受到深层的人生道理。"
    },
    {
        "songName": "快乐小孩",
        "workName": "大耳朵图图1&2",
        "impression": "印象深刻",
        "releaseYear": "2005",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1PM411Z7QK/",
        "cover": "images/大耳朵图图1.webp",
        "description": "动画《大耳朵图图》的主题曲，展现了幼儿园小朋友图图天真可爱的日常生活。歌曲轻快欢乐，充满了童趣，描绘了一个普通家庭中孩子快乐成长的故事。图图的大耳朵和奇思妙想给无数观众带来了欢乐。"
    },
    {
        "songName": "左手右手",
        "workName": "喜羊羊与灰太狼",
        "impression": "印象深刻",
        "releaseYear": "2005",
        "singer": "",
        "type": "",
        "bilibiliLink": "https://www.bilibili.com/video/BV1y44y187JS/",
        "cover": "images/喜羊羊与灰太狼.webp",
        "description": "《喜羊羊与灰太狼》系列中的经典插曲，歌词简单重复但极具感染力。'左手右手一个慢动作'成为了当年最流行的儿歌之一，几乎所有小朋友都会跟着唱跳。这首歌充满了童真和快乐，是00后集体记忆的重要组成部分。"
    },
    {
        "songName": "天眼少年",
        "workName": "天眼",
        "impression": "基本无印象",
        "releaseYear": "2005",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1Cj411y7dz/",
        "cover": "images/天眼.webp",
        "description": "国产科幻动画《天眼》的主题曲，讲述了拥有天眼能力的少年与邪恶势力战斗的故事。歌曲充满了科幻感和正义感，展现了中国早期科幻动画的探索精神。动画融合了中国传统文化元素与现代科幻题材。"
    },
    {
        "songName": "阳光男孩阳光女孩",
        "workName": "家有儿女",
        "impression": "印象深刻",
        "releaseYear": "2005",
        "singer": "TG4",
        "type": "插曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1Kb411i7JJ/",
        "cover": "images/家有儿女.webp",
        "description": "情景喜剧《家有儿女》中的经典插曲，由TG4演唱。这首歌充满了青春活力和阳光气息，表达了孩子们对美好生活的向往。'阳光男孩阳光女孩，阳光照进我们的家'的歌词温暖人心，成为了00后童年家庭生活的真实写照。"
    },
    {
        "songName": "问题小孩",
        "workName": "大耳朵图图1&2",
        "impression": "印象深刻",
        "releaseYear": "2005",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1GU4y1S7VQ/",
        "cover": "images/大耳朵图图2.webp",
        "description": "《大耳朵图图》的另一首主题曲，幽默风趣地描绘了图图这个'问题小孩'的形象。歌曲展现了孩子成长过程中的调皮捣蛋和天真烂漫，让家长们在会心一笑的同时，也理解了孩子成长的不易。图图的可爱形象深入人心。"
    },
    {
        "songName": "人生不过一百年",
        "workName": "虹猫蓝兔七侠传",
        "impression": "有一些印象",
        "releaseYear": "2006",
        "singer": "",
        "type": "片头曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1ss411w7Ri/",
        "cover": "images/虹猫蓝兔七侠传.webp",
        "description": "国产武侠动画《虹猫蓝兔七侠传》的片头曲，充满了江湖侠义气息。歌曲旋律大气磅礴，'人生不过一百年，何不潇洒走一回'的歌词展现了武侠精神。这部动画是中国武侠动画的巅峰之作，将传统武侠文化传递给了新一代。"
    },
    {
        "songName": "生命的云彩",
        "workName": "憨八龟的故事",
        "impression": "基本无印象",
        "releaseYear": "2006",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1Vp4y1Q7qm/",
        "cover": "images/憨八龟的故事.webp",
        "description": "动画《憨八龟的故事》的主题曲，讲述了一只可爱的乌龟在生活中的各种趣事。歌曲温馨柔和，充满了童话色彩，传递着简单快乐的生活态度。憨八龟憨厚可爱的形象给孩子们留下了深刻印象。"
    },
    {
        "songName": "心中想的还是他",
        "workName": "虹猫蓝兔七侠传",
        "impression": "有一些印象",
        "releaseYear": "2006",
        "singer": "",
        "type": "片尾曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1sx411Q7rQ/",
        "cover": "images/虹猫蓝兔七侠传.webp",
        "description": "《虹猫蓝兔七侠传》的片尾曲，歌曲柔美动人，描绘了蓝兔对虹猫的深情。这首歌为这部武侠动画增添了一抹温柔的感情色彩，让观众在热血江湖之外，也能感受到细腻的情感。虹猫和蓝兔的情谊成为了动画的一大亮点。"
    },
    {
        "songName": "米奇妙妙屋",
        "workName": "米奇妙妙屋",
        "impression": "有一些印象",
        "releaseYear": "2006",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1kt411t74e/",
        "cover": "images/米奇妙妙屋.webp",
        "description": "迪士尼经典动画《米奇妙妙屋》的主题曲，欢快的旋律和简单的歌词深受幼儿喜爱。'米奇妙妙屋，欢迎来到米奇妙妙屋'的开场白成为了无数孩子的启蒙回忆。这部动画通过互动的方式教孩子们数字、形状等基础知识。"
    },
    {
        "songName": "梦的光点",
        "workName": "神兵小将",
        "impression": "印象深刻",
        "releaseYear": "2007",
        "singer": "",
        "type": "",
        "bilibiliLink": "https://www.bilibili.com/video/BV1dr4y1G7JQ/",
        "cover": "images/神兵小将.webp",
        "description": "国产3D动画《神兵小将》的主题曲，充满了热血和梦想。歌曲讲述了少年南宫问天等人为了守护家园而战斗的故事，'梦的光点照亮前方'传递着永不放弃的精神。这部动画以精良的制作和深刻的主题赢得了好评。"
    },
    {
        "songName": "猪猪侠",
        "workName": "猪猪侠",
        "impression": "印象深刻",
        "releaseYear": "2007",
        "singer": "",
        "type": "",
        "bilibiliLink": "https://www.bilibili.com/video/BV15D4y1o7k6/",
        "cover": "images/猪猪侠.webp",
        "description": "国产动画《猪猪侠》的主题曲，讲述了一只可爱的小猪英雄保护童话世界的故事。歌曲轻快有趣，展现了猪猪侠虽然平凡但勇敢正义的形象。这部动画以其幽默的风格和正能量的主题成为了中国原创动画的代表作之一。"
    },
    {
        "songName": "天下第一",
        "workName": "神厨小福贵",
        "impression": "基本无印象",
        "releaseYear": "2007",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1UX4y1v769/",
        "cover": "images/神厨小福贵.webp",
        "description": "动画《神厨小福贵》的主题曲，讲述了少年福贵学习厨艺、追求梦想的故事。歌曲充满了励志色彩，展现了中国饮食文化的魅力。动画通过厨艺比拼传递着坚持不懈、精益求精的工匠精神。"
    },
    {
        "songName": "小鲤鱼历险记",
        "workName": "小鲤鱼历险记",
        "impression": "有一些印象",
        "releaseYear": "2007",
        "singer": "韩磊",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1KW411C7cg/",
        "cover": "images/小鲤鱼历险记.webp",
        "description": "由韩磊演唱的《小鲤鱼历险记》主题曲，讲述了小鲤鱼泡泡寻找龙鳞、拯救家园的冒险故事。歌曲旋律优美动听，充满了传奇色彩。'小小鲤鱼，游啊游'的歌词朗朗上口，成为了许多人的童年回忆。这部动画融合了中国传统神话元素。"
    },
    {
        "songName": "闪电冲线",
        "workName": "雷速登闪电冲线",
        "impression": "印象深刻",
        "releaseYear": "2007",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV13W411X7tv/",
        "cover": "images/雷速登闪电冲线.webp",
        "description": "动画《雷速登闪电冲线》的主题曲，讲述了少年们驾驶遥控赛车竞技的故事。歌曲节奏快速激烈，充满了竞速的激情和热血。'闪电冲线，冲向胜利'的歌词激励着孩子们勇于挑战。这部动画带动了当年遥控赛车的热潮。"
    },
    {
        "songName": "月光",
        "workName": "秦时明月",
        "impression": "有一些印象",
        "releaseYear": "2007",
        "singer": "胡彦斌",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1dt4y1v7AZ/",
        "cover": "images/秦时明月.webp",
        "description": "由胡彦斌演唱的《秦时明月》主题曲，这部国产3D武侠动画以精良的制作和深刻的主题成为经典。歌曲意境优美，'沧海一声笑，明月照千秋'展现了家国情怀和侠义精神。秦时明月系列将中国历史与武侠文化完美融合。"
    },
    {
        "songName": "小英雄大肚腩",
        "workName": "猪猪侠",
        "impression": "印象深刻",
        "releaseYear": "2007",
        "singer": "",
        "type": "",
        "bilibiliLink": "https://www.bilibili.com/video/BV1nh4y1p7Qd/",
        "cover": "images/猪猪侠.webp",
        "description": "《猪猪侠》系列中的一首经典歌曲，幽默诙谐地展现了猪猪侠的形象特点。'小英雄大肚腩'这个反差萌的设定让角色更加可爱亲切，告诉孩子们英雄不一定要完美，重要的是有一颗正义的心。"
    },
    {
        "songName": "哈皮之歌",
        "workName": "哈皮父子",
        "impression": "基本无印象",
        "releaseYear": "2007",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV14y4y157Fo/",
        "cover": "images/哈皮父子.webp",
        "description": "动画《哈皮父子》的主题曲,讲述了父子俩温馨搞笑的日常生活。歌曲轻松欢快，展现了家庭的温暖和亲子关系的重要性。动画通过简单的故事传递着家庭教育的智慧和父爱如山的主题。"
    },
    {
        "songName": "不怕",
        "workName": "神兵小将",
        "impression": "印象深刻",
        "releaseYear": "2007",
        "singer": "",
        "type": "",
        "bilibiliLink": "https://www.bilibili.com/video/BV1oD4y1D7oS/",
        "cover": "images/神兵小将.webp",
        "description": "《神兵小将》中的另一首经典歌曲，充满了勇气和力量。'不怕困难不怕险'的歌词激励着孩子们面对挑战时要勇敢坚强。这首歌完美诠释了动画中少年们不畏艰险、守护正义的精神。"
    },
    {
        "songName": "中华小子",
        "workName": "中华小子",
        "impression": "有一些印象",
        "releaseYear": "2007",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1EW41157N7/",
        "cover": "images/中华小子.webp",
        "description": "中法合拍动画《中华小子》的主题曲，讲述了三位少年学习少林功夫、保护世界的故事。歌曲融合了东西方音乐元素，展现了中国功夫文化的魅力。这部动画以其独特的美术风格和国际化视角获得了广泛好评。"
    },
    {
        "songName": "超级棒棒糖",
        "workName": "猪猪侠",
        "impression": "印象深刻",
        "releaseYear": "2007",
        "singer": "",
        "type": "",
        "bilibiliLink": "https://www.bilibili.com/video/BV1c4411W7uX/",
        "cover": "images/猪猪侠.webp",
        "description": "《猪猪侠》中的经典插曲，歌曲充满童趣，描绘了变身道具'超级棒棒糖'的神奇力量。'吃了超级棒棒糖，我就是超人'的歌词激发了孩子们的想象力，成为了当年最受欢迎的儿歌之一。"
    },
    {
        "songName": "风已吹散",
        "workName": "夺宝幸运星/开心西游记",
        "impression": "基本无印象",
        "releaseYear": "2007",
        "singer": "",
        "type": "",
        "bilibiliLink": "https://www.bilibili.com/video/BV1kh411P7rh/",
        "cover": "images/夺宝幸运星.webp",
        "description": "动画《夺宝幸运星》(又名《开心西游记》)的歌曲，以西游记为背景展开的全新故事。歌曲旋律悠扬，带有一些淡淡的离别与成长情绪，为这部趣味冒险动画增添了更多层次。"
    },
    {
        "songName": "穿越（片头版）",
        "workName": "魔幻手机",
        "impression": "有一些印象",
        "releaseYear": "2008",
        "singer": "",
        "type": "片头曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1GP411M7Jn/",
        "cover": "images/魔幻手机.webp",
        "description": "科幻喜剧《魔幻手机》的片头曲，讲述了一部神奇的手机带来的奇幻冒险。歌曲充满了未来感和神秘色彩，'穿越时空的界限'展现了无限可能。这部剧以其脑洞大开的剧情和幽默的风格深受观众喜爱。"
    },
    {
        "songName": "快乐星猫",
        "workName": "快乐星猫",
        "impression": "印象深刻",
        "releaseYear": "2008",
        "singer": "牛奶咖啡",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1Gq4y1e73q/",
        "cover": "images/快乐星猫.webp",
        "description": "由牛奶咖啡组合演唱的《快乐星猫》主题曲，讲述了十二星座战士保护星猫的故事。歌曲轻快时尚，充满了青春活力。'快乐星猫，跟我来'的歌词朗朗上口，动画将星座文化与冒险故事巧妙结合。"
    },
    {
        "songName": "机战王",
        "workName": "洛洛历险记",
        "impression": "有一些印象",
        "releaseYear": "2008",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1RU4y1F7Cd/",
        "cover": "images/洛洛历险记.webp",
        "description": "机甲动画《洛洛历险记》的主题曲，讲述了机车侠们守护世界和平的故事。歌曲充满了科技感和战斗激情，'机战王，出发'激励着少年们勇敢战斗。这部动画是中国机甲动画的代表作之一。"
    },
    {
        "songName": "小鸡不好惹",
        "workName": "小鸡不好惹",
        "impression": "基本无印象",
        "releaseYear": "2008",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1va411r7iS/",
        "cover": "images/小鸡不好惹.webp",
        "description": "动画《小鸡不好惹》的主题曲，讲述了一群小鸡的搞笑日常。歌曲幽默风趣，'小鸡不好惹'的态度展现了即使弱小也要勇敢的精神。动画以其独特的画风和轻松的故事赢得了观众的喜爱。"
    },
    {
        "songName": "巴啦啦小魔仙",
        "workName": "巴啦啦小魔仙",
        "impression": "印象深刻",
        "releaseYear": "2008",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV17x411977R/",
        "cover": "images/巴啦啦小魔仙.webp",
        "description": "少女魔法剧《巴啦啦小魔仙》的主题曲，开启了中国真人魔法少女剧的先河。'巴啦啦能量，乌卡拉卡'的变身咒语成为了一代人的集体记忆。这部剧让无数女孩相信魔法的力量，追逐着成为魔仙的梦想。"
    },
    {
        "songName": "穿越（片尾版）",
        "workName": "魔幻手机",
        "impression": "有一些印象",
        "releaseYear": "2008",
        "singer": "",
        "type": "片尾曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1Xk4y1V7kB/",
        "cover": "images/魔幻手机.webp",
        "description": "《魔幻手机》的片尾曲版本，旋律更加舒缓温柔，为每集精彩的故事画上圆满的句号。歌曲带着一丝回味与思考，让观众在欢笑之余也能感受到穿越时空背后的深意。"
    },
    {
        "songName": "我的未来式",
        "workName": "爱情公寓",
        "impression": "有一些印象",
        "releaseYear": "2009",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1TJ411n7w5/",
        "cover": "images/爱情公寓.webp",
        "description": "情景喜剧《爱情公寓》的主题曲，讲述了一群年轻人在爱情公寓的搞笑日常。歌曲充满了青春气息和对未来的憧憬，'这是我的未来式'表达了年轻人追梦的态度。这部剧陪伴了整整一代人的青春。"
    },
    {
        "songName": "我们有力量",
        "workName": "圣石奇兵",
        "impression": "基本无印象",
        "releaseYear": "2009",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV13W411Z7hj/",
        "cover": "images/圣石奇兵.webp",
        "description": "动画《圣石奇兵》的主题曲，讲述了少年们守护圣石、对抗邪恶的冒险故事。歌曲充满力量感，'我们有力量'传递着团结就是力量的主题。动画融合了科幻与奇幻元素，展现了少年们的成长。"
    },
    {
        "songName": "爱不会绝迹",
        "workName": "恐龙宝贝",
        "impression": "有一些印象",
        "releaseYear": "2009",
        "singer": "林俊杰",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1pK411j7YG/",
        "cover": "images/恐龙宝贝.webp",
        "description": "由林俊杰演唱的《恐龙宝贝》主题曲，讲述了现代少年与恐龙伙伴的冒险故事。歌曲旋律优美动听，'爱不会绝迹'传递着友谊和爱的永恒主题。林俊杰温暖的声音为这部动画增添了更多感染力。"
    },
    {
        "songName": "星空物语",
        "workName": "一起来看流星雨",
        "impression": "有一些印象",
        "releaseYear": "2009",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1JQ4y1P7oe/",
        "cover": "images/一起来看流星雨.webp",
        "description": "青春偶像剧《一起来看流星雨》的主题曲，讲述了平凡女孩与四位富二代的浪漫故事。歌曲充满了青春梦幻的气息，'让我们一起看流星雨'成为了当年最浪漫的约定。这部剧掀起了一阵青春偶像剧热潮。"
    },
    {
        "songName": "大角牛之歌",
        "workName": "小牛向前冲",
        "impression": "有一些印象",
        "releaseYear": "2009",
        "singer": "韩磊",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1MJ411R7Tn/",
        "cover": "images/小牛向前冲.webp",
        "description": "由韩磊演唱的《小牛向前冲》主题曲，讲述了小牛大角为了梦想奋斗的故事。韩磊浑厚有力的嗓音完美诠释了永不放弃的精神，'向前冲'的态度激励着孩子们勇敢追梦。"
    },
    {
        "songName": "《电击小子》主题曲",
        "workName": "电击小子",
        "impression": "印象深刻",
        "releaseYear": "2009",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1BW411Q7qG/",
        "cover": "images/电击小子.webp",
        "description": "科幻动画《电击小子》的主题曲，讲述了少年阿丁在虚拟世界冒险的故事。歌曲充满了电子感和未来科技色彩，展现了虚拟与现实交织的奇幻世界。动画探讨了网络时代的成长主题。"
    },
    {
        "songName": "Mojospy",
        "workName": "魔角侦探",
        "impression": "基本无印象",
        "releaseYear": "2009",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1ws411c7L7/",
        "cover": "images/魔角侦探.webp",
        "description": "侦探动画《魔角侦探》的主题曲，讲述了少年侦探破解谜案的故事。歌曲充满了神秘感和推理氛围，激发着孩子们的好奇心和观察力。动画将侦探元素与奇幻冒险巧妙结合。"
    },
    {
        "songName": "光的战役",
        "workName": "铠甲勇士1",
        "impression": "印象深刻",
        "releaseYear": "2009",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1Rx4y1K7mZ/",
        "cover": "images/铠甲勇士1.webp",
        "description": "特摄剧《铠甲勇士》的主题曲，开创了中国本土特摄的新纪元。'这是光的战役'展现了正义与邪恶的较量，'合体！铠甲勇士！'的变身口号激动人心。这部剧让中国孩子也有了属于自己的超级英雄。"
    },
    {
        "songName": "超智能足球",
        "workName": "超智能足球",
        "impression": "有一些印象",
        "releaseYear": "2010",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1jJ411X744/",
        "cover": "images/超智能足球.webp",
        "description": "体育动画《超智能足球》的主题曲，将足球运动与科技元素结合。歌曲充满了运动激情和竞技精神，展现了少年们在绿茵场上挥洒汗水、追逐梦想的故事。动画传递着团队合作和永不放弃的体育精神。"
    },
    {
        "songName": "心灵就是战场",
        "workName": "赛尔号",
        "impression": "印象深刻",
        "releaseYear": "2010",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1AB4y1Q7FW/",
        "cover": "images/赛尔号.webp",
        "description": "网络游戏改编动画《赛尔号》的主题曲，讲述了赛尔机器人探索宇宙的冒险故事。'心灵就是战场'传递着勇气和信念的力量。赛尔号IP红遍了整个中国，成为了00后一代的集体回忆。"
    },
    {
        "songName": "像你这样的大师",
        "workName": "十二生肖闯江湖",
        "impression": "有一些印象",
        "releaseYear": "2010",
        "singer": "",
        "type": "片尾曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1UP411t7Uj/",
        "cover": "images/十二生肖闯江湖.webp",
        "description": "动画《十二生肖闯江湖》的片尾曲，以中国传统十二生肖为主角展开冒险。歌曲幽默风趣，展现了各具特色的生肖形象。动画将传统文化与现代故事巧妙结合，寓教于乐。"
    },
    {
        "songName": "飞翔吧！神圣战机",
        "workName": "弹珠传说",
        "impression": "有一些印象",
        "releaseYear": "2010",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1944y1v7aA/",
        "cover": "images/弹珠传说.webp",
        "description": "竞技动画《弹珠传说》的主题曲，讲述了少年们玩弹珠战斗的热血故事。歌曲充满了战斗激情，'飞翔吧！神圣战机'的呼喊激动人心。动画带动了当年弹珠玩具的流行。"
    },
    {
        "songName": "我不怕",
        "workName": "晶码战士",
        "impression": "有一些印象",
        "releaseYear": "2010",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1mx421f7mL/",
        "cover": "images/晶码战士.webp",
        "description": "科幻动画《晶码战士》的主题曲，讲述了数码世界的冒险故事。'我不怕'的歌词传递着勇敢面对困难的精神，鼓励孩子们在成长中克服恐惧，勇往直前。"
    },
    {
        "songName": "青春之火",
        "workName": "火力少年王",
        "impression": "印象深刻",
        "releaseYear": "2010",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1Us411m7SG/",
        "cover": "images/火力少年王.webp",
        "description": "竞技动画《火力少年王》的主题曲，讲述了少年们玩悠悠球竞技的热血故事。'青春之火永不熄灭'展现了少年们的激情与梦想。动画掀起了一股悠悠球热潮，成为了当年最受欢迎的玩具之一。"
    },
    {
        "songName": "十二生肖总动员",
        "workName": "十二生肖闯江湖",
        "impression": "有一些印象",
        "releaseYear": "2010",
        "singer": "",
        "type": "片头曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1ub41117Ye/",
        "cover": "images/十二生肖闯江湖.webp",
        "description": "《十二生肖闯江湖》的片头曲，欢快的旋律介绍了十二生肖的各个角色。歌曲朗朗上口，让孩子们在欢乐中了解中国传统的生肖文化，寓教于乐。"
    },
    {
        "songName": "再飞行",
        "workName": "星游记",
        "impression": "有一些印象",
        "releaseYear": "2011",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV114411x7gW/",
        "cover": "images/星游记.webp",
        "description": "国产科幻动画《星游记》的主题曲，讲述了少年麦当寻找父亲、探索宇宙的故事。'再飞行'充满了对梦想的执着和对未来的憧憬。这部动画以其精良的制作和感人的剧情获得了高度评价。"
    },
    {
        "songName": "不败的英雄",
        "workName": "铠甲勇士刑天",
        "impression": "印象深刻",
        "releaseYear": "2011",
        "singer": "",
        "type": "片头曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1GU4y1H74h/",
        "cover": "images/铠甲勇士刑天.webp",
        "description": "《铠甲勇士》系列第二部《刑天》的片头曲，延续了正义战胜邪恶的主题。'不败的英雄'展现了铠甲勇士永不言败的精神，歌曲更加成熟有力，陪伴了铠甲勇士系列的发展壮大。"
    },
    {
        "songName": "快乐女孩",
        "workName": "甜心格格",
        "impression": "有一些印象",
        "releaseYear": "2011",
        "singer": "刘惜君",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1AW411Z77y/",
        "cover": "images/甜心格格.webp",
        "description": "由刘惜君演唱的《甜心格格》主题曲，讲述了现代女孩穿越到古代成为格格的奇幻故事。歌曲甜美动听，充满了少女的梦幻气息，'做快乐女孩'传递着乐观积极的生活态度。"
    },
    {
        "songName": "斗龙战士",
        "workName": "斗龙战士",
        "impression": "基本无印象",
        "releaseYear": "2011",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1J34y1L7rn/",
        "cover": "images/斗龙战士.webp",
        "description": "动画《斗龙战士》的主题曲，讲述了少年们与龙伙伴并肩作战的故事。歌曲充满了战斗激情和友谊力量，展现了人与龙之间的深厚羁绊。动画融合了龙文化与现代冒险元素。"
    },
    {
        "songName": "超兽武装",
        "workName": "超兽武装",
        "impression": "有一些印象",
        "releaseYear": "2011",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1qP4y187Lf/",
        "cover": "images/超兽武装.webp",
        "description": "科幻动画《超兽武装》的主题曲，讲述了平行宇宙中正邪两大阵营的战斗故事。歌曲宏大磅礴，充满了史诗感。动画以其复杂的世界观和深刻的主题受到了年龄较大观众的喜爱。"
    },
    {
        "songName": "魁拔军歌",
        "workName": "魁拔1",
        "impression": "基本无印象",
        "releaseYear": "2011",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1q741167Fz/",
        "cover": "images/魁拔.webp",
        "description": "国产动画电影《魁拔》的主题曲，以其宏大的世界观和精良的制作成为国产动画的里程碑。'魁拔军歌'气势磅礴，展现了一个史诗般的奇幻世界。虽然票房不佳，但其艺术价值获得了高度认可。"
    },
    {
        "songName": "星力量",
        "workName": "宇宙星神",
        "impression": "基本无印象",
        "releaseYear": "2011",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1gW411H7sr/?spm_id_from=333.337.search-card.all.click&vd_source=73e512caa65b4b2e190a5832c65c1193",
        "cover": "images/宇宙星神.webp",
        "description": "特摄剧《宇宙星神》的主题曲，讲述了星神战队保卫地球的故事。歌曲充满了科幻感和正义力量，'星力量'代表着希望与勇气。这是中国本土特摄的又一次尝试。"
    },
    {
        "songName": "我还有点小糊涂",
        "workName": "熊出没",
        "impression": "印象深刻",
        "releaseYear": "2012",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1S4411c7Tm/",
        "cover": "images/熊出没.webp",
        "description": "国民动画《熊出没》的主题曲，讲述了熊大熊二和光头强之间的搞笑故事。'我还有点小糊涂'成为了光头强的经典台词，歌曲幽默风趣，深受小朋友喜爱。熊出没系列成为了中国最成功的动画IP之一。"
    },
    {
        "songName": "快乐酷宝",
        "workName": "快乐酷宝",
        "impression": "印象深刻",
        "releaseYear": "2012",
        "singer": "陈洁丽",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1gj411m75t/",
        "cover": "images/快乐酷宝.webp",
        "description": "由陈洁丽演唱的《快乐酷宝》主题曲，讲述了可爱的酷宝机器人守护城市的故事。歌曲轻快欢乐，充满了童趣和科技感。动画将机器人元素与儿童日常巧妙结合。"
    },
    {
        "songName": "疯狂果宝",
        "workName": "果宝特攻",
        "impression": "印象深刻",
        "releaseYear": "2012",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1hC411J74Y/",
        "cover": "images/果宝特攻.webp",
        "description": "动画《果宝特攻》的主题曲，将水果拟人化为英雄战队。'疯狂果宝'充满了欢乐和创意，歌曲节奏明快，展现了果宝们保卫水果世界的冒险故事。动画以其独特的创意和幽默风格深受喜爱。"
    },
    {
        "songName": "风起云涌",
        "workName": "战斗王之飓风战魂",
        "impression": "印象深刻",
        "releaseYear": "2012",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1y44y117bs/",
        "cover": "images/战斗王飓风战魂.webp",
        "description": "竞技动画《战斗王之飓风战魂》的主题曲，讲述了少年们玩陀螺竞技的热血故事。'风起云涌'展现了激烈的战斗场面和永不言败的精神。动画带动了陀螺玩具的新一轮热潮。"
    },
    {
        "songName": "春之歌",
        "workName": "名侦探柯南剧场版：第11名前锋",
        "impression": "有一些印象",
        "releaseYear": "2012",
        "singer": "生物股长",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1Js411M72F/",
        "cover": "images/名侦探柯南.webp",
        "description": "日本乐队生物股长演唱的柯南剧场版主题曲，充满了青春活力和希望。'春之歌'的旋律优美动听，为这部推理电影增添了温暖的色彩。柯南系列陪伴了几代人的成长。"
    },
    {
        "songName": "我和你",
        "workName": "神奇阿呦",
        "impression": "有一些印象",
        "releaseYear": "2013",
        "singer": "",
        "type": "片尾曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV19V411C76h/",
        "cover": "images/神奇阿呦.webp",
        "description": "动画《神奇阿呦》的片尾曲，讲述了可爱外星人阿呦的奇幻冒险。歌曲温馨动人，'我和你'传递着友谊和陪伴的温暖。动画以其可爱的角色设计和温馨的故事深受小朋友喜爱。"
    },
    {
        "songName": "誓约",
        "workName": "神魄",
        "impression": "基本无印象",
        "releaseYear": "2013",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1QT4y1L7mJ/",
        "cover": "images/神魄.jpeg",
        "description": "奇幻动画《神魄》的主题曲，讲述了古代神话世界的战斗故事。'誓约'充满了史诗感和悲壮色彩，展现了守护者们的坚定信念。动画将中国神话元素与现代叙事相结合。"
    },
    {
        "songName": "开心往前飞",
        "workName": "开心宝贝之开心超人",
        "impression": "印象深刻",
        "releaseYear": "2013",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1za4y1v7Rr/",
        "cover": "images/开心超人.webp",
        "description": "动画《开心超人》的主题曲，讲述了五个超人保卫星星球的故事。'开心往前飞'充满了正能量和乐观精神，鼓励孩子们保持开心快乐的心态。动画以其积极向上的主题和可爱的角色广受好评。"
    },
    {
        "songName": "火花",
        "workName": "你的名字",
        "impression": "有一些印象",
        "releaseYear": "2016",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1Ym421G76f/",
        "cover": "images/你的名字.webp",
        "description": "日本动画电影《你的名字》的主题曲之一，由RADWIMPS乐队演唱。歌曲充满了青春和浪漫气息，完美契合了电影唯美的画面和感人的故事。这部电影在中国也掀起了观影热潮，成为现象级作品。"
    },
    {
        "songName": "打上花火",
        "workName": "烟花",
        "impression": "有一些印象",
        "releaseYear": "2017",
        "singer": "",
        "type": "主题曲",
        "bilibiliLink": "https://www.bilibili.com/video/BV1Ax411x7ak/",
        "cover": "images/烟花_打上花火.webp",
        "description": "日本动画电影《烟花》的主题曲，由DAOKO和米津玄师合作演唱。歌曲充满了夏日的青春气息和淡淡的忧伤，'打上花火'描绘了少年少女朦胧的情感。电影以其独特的艺术风格和深刻的主题引发思考。"
    }
];

// 默认封面和介绍
const DEFAULT_COVER = 'images/背景.jpg';
const DEFAULT_DESCRIPTION = '这是一首经典的童年影视歌曲，承载着许多人的美好回忆。每当熟悉的旋律响起，都能唤起那段纯真美好的童年时光。';

// 处理数据，确保每首歌都有封面和介绍
songsData.forEach(song => {
    if (!song.cover) song.cover = DEFAULT_COVER;
    if (!song.description) song.description = DEFAULT_DESCRIPTION;
});